name: Bench

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./

env:
  CFLAGS: -s -flto -DNDEBUG -DTIME_ALL

jobs:
  Bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - run: sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu kinetic universe'
    - run: sudo apt-get install -y tup re2c lemon libxxhash-dev llvm-dev valgrind
    - run: |
        pushd /usr/include
        [ -f hedley.h ] || sudo wget https://raw.githubusercontent.com/nemequ/hedley/master/hedley.h -O ./hedley.h
        predef() {
          sudo svn checkout https://github.com/natefoo/predef/trunk/predef
        }
        [ -d predef ] || predef
        popd
    - run: sed -i 's/\^j\^//g' Tupfile
    - run: "[ -f .tup/db ] || tup init"
    - run: ". scripts/environment.sh && tup"
    - run: git reset --hard
    - run: ./test bench -j
    - run: ./scripts/collect-size-metrics.sh > sizes.json
    - run: ./scripts/merge-metrics.sh sizes.json bench.json > metrics.json
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Language Compiler Metrics
        # What benchmark tool the output.txt came from
        tool: 'customSmallerIsBetter'
        # Where the output from the benchmark tool is stored
        output-file-path: ./metrics.json
        # Workflow will fail when an alert happens
        fail-on-alert: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        benchmark-data-dir-path: bench/compiler
