name: Bench

on:
  push:
    branches:
      - os/continuous-benchmarks

defaults:
  run:
    working-directory: ./

env:
  CFLAGS: -DTIME_ALL

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webiny/action-conventional-commits@v1.1.0
    - run: sudo apt install -y tup
    - run: tup
    - run: ./test bench -j
    - name: Download previous benchmark data
      uses: actions/cache@v1
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Language Compiler Benchmark
        # What benchmark tool the output.txt came from
        tool: 'customSmallerIsBetter'
        # Where the output from the benchmark tool is stored
        output-file-path: ./bench.json
        # Workflow will fail when an alert happens
        fail-on-alert: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
