name: CI (without nix)

on:
  - pull_request

defaults:
  run:
    working-directory: ./

env:
  NIXPKGS_ALLOW_BROKEN: 1

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webiny/action-conventional-commits@v1.1.0
    - run: sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu kinetic universe'
    - run: sudo apt-get install -y tup re2c lemon libxxhash-dev llvm-dev
    - run: sed -i 's/\^j\^//g' Tupfile
    - run: |
        . scripts/environment.sh
        echo LLVM: $LLVM_CONFIG_FLAGS
        tup generate build.sh
        sed -i '1 s/$/\nset -x/' build.sh
        ./build.sh
    - run: "[ -f .tup/db ] || tup init"
    - run: tup
    - run: ./test --lite
