name: CI

on:
  - push
  - pull_request

defaults:
  run:
    working-directory: ./

env:
  NIXPKGS_ALLOW_BROKEN: 1

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v17
    - run: nix build
    - run: nix flake check --impure
    - name: Download previous benchmark data
      uses: actions/cache@v1
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark
    - run: nix build .#lang-c-benchmark
