name: CI

on:
  - push
  - pull_request

defaults:
  run:
    working-directory: ./

env:
  NIXPKGS_ALLOW_BROKEN: 1

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webiny/action-conventional-commits@v1.1.0
    - name: Install Nix
      uses: cachix/install-nix-action@v17
    - run: nix build
    - run: nix flake check --impure
