name: Tests

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./

env:
  CFLAGS: -O1 -g 

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
    - uses: webiny/action-conventional-commits@v1.1.0
    - uses: actions/checkout@v2
    - run: ./scripts/checks/formatting.sh
    - run: ./scripts/checks/headers-have-pragmas.sh
    - run: ./scripts/checks/licences.sh
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: tup re2c lemon libxxhash-dev llvm-dev valgrind gcc g++ pkg-config libreadline-dev subversion
        version: 1.0
    - run: |
        pushd /usr/include
        [ -f hedley.h ] || sudo wget https://raw.githubusercontent.com/nemequ/hedley/master/hedley.h -O ./hedley.h
        predef() {
          sudo svn checkout https://github.com/natefoo/predef/trunk/predef
        }
        [ -d predef ] || predef
        popd
    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build
    - run: ./build/test-exe --lite -j

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: 'test-results.xml'

    - run: valgrind --leak-check=full --error-exitcode=1 ./build/test-exe --lite
